export const workspaceCards = [
  {
    title: "Roadmap Development",
    href: "/roadmap",
    eyebrow: "Start here",
    description: "Build the consultant-style plan: scope SI, map information flow, define assets, identify gaps, and prepare the path to Level 1 self-assessment.",
  },
  {
    title: "CPCSC Level 1 Controls",
    href: "/controls",
    eyebrow: "Do the work",
    description: "Implement the 13 required controls, record implementation details, assign owners, and attach evidence references.",
  },
  {
    title: "Tools and Templates",
    href: "/resources",
    eyebrow: "Work aids",
    description: "Use guided worksheets, policy starters, evidence planning tools, owner trackers, and review templates as part of the readiness workflow.",
  },
  {
    title: "Reports",
    href: "/reports",
    eyebrow: "Show progress",
    description: "Create the compliance assessment package for internal review, leadership conversations, and self-assessment support.",
  },
];

export const roadmapSteps = [
  {
    step: "1",
    title: "Scoping",
    description: "Identify the federal Specified Information environment before applying controls. This is the first place a consultant would normally start.",
    tasks: [
      "Identify Specified Information (SI) and controlled/protected information not intended for public release.",
      "Map information flow: how SI is received, stored, processed, transmitted, shared, archived, and disposed of.",
      "Define in-scope assets: devices, applications, cloud services, removable media, repositories, users, and administrators.",
    ],
    cta: { label: "Open SI scoping tool", href: "/resources#specified-information-scope" },
  },
  {
    step: "2",
    title: "Implement the 13 required controls",
    description: "Translate the Level 1 controls into operational practices your organization can explain and maintain.",
    tasks: [
      "Access Control: limit system access to authorized users and processes with need-to-know permissions.",
      "Identification & Authentication: use unique user IDs and multifactor authentication where required.",
      "System Integrity: maintain anti-malware protection and patch management routines.",
      "Physical Protection: secure physical access to systems and maintain visitor/access records.",
      "Media Protection: sanitize, destroy, or control media and devices that contain SI.",
    ],
    cta: { label: "Open Level 1 controls", href: "/controls" },
  },
  {
    step: "3",
    title: "Assessment and evidence collection",
    description: "Evaluate current posture against the objectives and build an evidence pack that supports the self-assessment record.",
    tasks: [
      "Conduct a gap analysis against the 13 Level 1 controls and official criteria.",
      "Collect evidence references such as access lists, MFA configuration screens, security policies, device-use rules, training records, maintenance logs, and review sign-offs.",
      "Retain supporting evidence and make sure each record is current, understandable, and tied to the scoped SI environment.",
    ],
    cta: { label: "Open evidence toolkit", href: "/resources#evidence-folder-structure" },
  },
  {
    step: "4",
    title: "Self-assessment and attestation support",
    description: "Prepare the information needed before using Government of Canada self-assessment and supplier profile workflows.",
    tasks: [
      "Confirm CanadaBuys account and supplier profile readiness.",
      "Use the Cyber Centre/Government of Canada self-assessment process to verify implementation status.",
      "Record attestation dates, renewal timing, internal reviewer, and evidence package location.",
    ],
    cta: { label: "Open reports", href: "/reports" },
  },
];

export const resourceItems = [
  { title: "Separation of duties worksheet", href: "/resources/separation-of-duties-worksheet.md", description: "Map duties, conflicts, mitigations, and follow-up owners." },
  { title: "Control owner assignment tracker", href: "/resources/control-owner-assignment-tracker.md", description: "Assign each CPCSC control to an accountable owner and track next actions." },
  { title: "Evidence folder structure guide", href: "/resources/evidence-folder-structure-guide.md", description: "Create a practical source-evidence folder structure and naming convention." },
  { title: "Quarterly access review template", href: "/resources/quarterly-access-review-template.md", description: "Document user access reviews, exceptions, remediation, and sign-off." },
  { title: "System inventory worksheet", href: "/resources/system-inventory-worksheet.md", description: "Define systems, owners, data handled, criticality, and readiness scope." },
  { title: "Specified Information scope worksheet", href: "/resources/specified-information-scope-worksheet.md", description: "Map where federal SI content exists, who accesses it, and which tools handle it." },
  { title: "Policy template starter pack", href: "/resources/policy-template-starter-pack.md", description: "Starter outlines for access control, acceptable use, incident response, asset management, password/MFA, media disposal, and public-content review policies." },
];

export const resourceToolkits = [
  {
    id: "specified-information-scope",
    title: "Specified Information scope builder",
    stage: "Roadmap step 1",
    value: "Defines what is in scope before the organization spends time implementing controls in the wrong places.",
    outcome: "SI inventory, information flow map, in-scope systems, people with access, and open scope questions.",
    downloadHref: "/resources/specified-information-scope-worksheet.md",
    primaryHref: "/settings",
    primaryLabel: "Update SI scope fields",
    fields: ["Contract / program context", "SI content inventory", "Storage and processing locations", "Transmission paths", "People and roles with access", "Scope boundaries", "Evidence locations"],
    evidence: ["Data flow or architecture diagram", "System inventory export", "Access list or role matrix", "Cloud/service-provider location evidence", "Scope approval or sign-off"],
    sample: "Example output: SI is received through buyer email and CanadaBuys artifacts, stored in Microsoft 365 Canada, processed by Engineering and Contracts roles, and included in Level 1 scope for endpoints, SharePoint, email, and MDM-managed laptops.",
  },
  {
    id: "system-inventory",
    title: "System inventory builder",
    stage: "Roadmap step 1",
    value: "Turns vague IT scope into a concrete asset list that control owners can actually review.",
    outcome: "List of in-scope devices, apps, SaaS tools, cloud services, removable media, owners, users, hosting locations, and criticality.",
    downloadHref: "/resources/system-inventory-worksheet.md",
    primaryHref: "/settings",
    primaryLabel: "Update organization scope",
    fields: ["System / asset name", "Business purpose", "Owner", "Users or roles", "Data handled", "Hosting/location", "Criticality", "In-scope decision"],
    evidence: ["Endpoint inventory", "SaaS application list", "Cloud region configuration", "MDM or device-management export", "Network/environment boundary notes"],
    sample: "Example output: M365, company laptops, password manager, MDM, file shares, and project repositories are in scope because they store, process, or provide access to SI.",
  },
  {
    id: "control-owner-assignment",
    title: "Control owner assignment board",
    stage: "Roadmap step 2",
    value: "Makes the 13 CPCSC controls accountable instead of abstract.",
    outcome: "Each control has an owner, backup owner, status, evidence location, next action, and due date.",
    downloadHref: "/resources/control-owner-assignment-tracker.md",
    primaryHref: "/controls",
    primaryLabel: "Assign control owners",
    fields: ["Control", "Control family", "Owner", "Backup owner", "Current status", "Evidence location", "Next action", "Due date"],
    evidence: ["Owner assignment tracker", "Control implementation notes", "Review cadence", "Leadership decision log"],
    sample: "Example output: Identification & Authentication is owned by IT Operations, due this month, with MFA configuration screenshots and access review exports listed as supporting evidence.",
  },
  {
    id: "policy-starter-pack",
    title: "Policy starter pack",
    stage: "Roadmap step 2",
    value: "Helps teams create practical rules that match how they actually protect SI, instead of staring at a blank policy document.",
    outcome: "Starter policy outlines for access control, acceptable use, incident response, asset management, MFA/password rules, media disposal, and public-content review.",
    downloadHref: "/resources/policy-template-starter-pack.md",
    primaryHref: "/settings",
    primaryLabel: "Record short security rules",
    fields: ["Purpose", "Scope", "Roles and responsibilities", "Required practices", "Exceptions", "Evidence and records", "Review cadence"],
    evidence: ["Approved policies", "Short employee rules", "Training acknowledgement", "Review/sign-off record", "Exception register"],
    sample: "Example output: A short access-control policy explains account provisioning, MFA, privileged access, access reviews, offboarding, exceptions, and where evidence is retained.",
  },
  {
    id: "quarterly-access-review",
    title: "Quarterly access review workflow",
    stage: "Roadmap step 3",
    value: "Creates repeatable proof that access remains limited to people with a business need.",
    outcome: "Completed access review record with reviewer, business owner, exceptions, remediation actions, completion dates, and sign-off.",
    downloadHref: "/resources/quarterly-access-review-template.md",
    primaryHref: "/controls",
    primaryLabel: "Attach access evidence",
    fields: ["Review period", "System/application", "Business owner", "Technical owner", "Reviewer", "User access table", "Exceptions", "Sign-off"],
    evidence: ["Access list", "MFA/admin screenshots", "Removed-user evidence", "Exception remediation log", "Reviewer sign-off"],
    sample: "Example output: Quarterly M365 access review confirms active users, removes one stale guest account, records the remediation owner, and stores the signed review in the evidence folder.",
  },
  {
    id: "separation-of-duties",
    title: "Separation of duties review",
    stage: "Roadmap step 3",
    value: "Identifies where one person can request, approve, implement, and review the same sensitive action.",
    outcome: "Conflict list, compensating controls, follow-up owner, target completion date, and evidence location.",
    downloadHref: "/resources/separation-of-duties-worksheet.md",
    primaryHref: "/controls",
    primaryLabel: "Record control evidence",
    fields: ["Process reviewed", "Business owner", "Key duties", "Assigned roles", "Conflict checks", "Mitigations", "Follow-up owner", "Evidence location"],
    evidence: ["Role matrix", "Approval workflow screenshot", "Privileged access review", "Mitigation decision", "Follow-up completion record"],
    sample: "Example output: The same admin can approve and implement access changes, so the organization adds manager approval and quarterly review as a compensating control.",
  },
  {
    id: "evidence-folder-structure",
    title: "Evidence pack organizer",
    stage: "Roadmap step 3",
    value: "Keeps evidence easy to find, understand, and explain later while source files remain in the approved repository.",
    outcome: "Folder structure, naming convention, evidence record checklist, and control-to-proof map.",
    downloadHref: "/resources/evidence-folder-structure-guide.md",
    primaryHref: "/controls",
    primaryLabel: "Add evidence references",
    fields: ["Evidence title", "Control supported", "Evidence type", "Storage path/reference", "Owner", "Date created", "Date reviewed", "What it proves", "Limitations/follow-up"],
    evidence: ["Evidence folder index", "Naming convention", "Control evidence register", "Reports/export package", "Review notes"],
    sample: "Example output: Evidence is stored in CPCSC Readiness/05-Identification-and-Authentication with dated MFA screenshots and a clear note explaining what each screenshot proves.",
  },
];

export const futureRoadmaps = [
  {
    title: "CPCSC Level 2 roadmap",
    description: "Future support area for the larger control set and third-party audit readiness. Keep Level 1 complete and evidence-backed before expanding scope.",
  },
  {
    title: "CPCSC Level 3 roadmap",
    description: "Future support area for advanced requirements, government audit expectations, and deeper security architecture documentation.",
  },
  {
    title: "ITSP.10.171 / NIST SP 800-171 Rev. 3 expansion",
    description: "Optional future expansion for documenting the broader security architecture and how each control is implemented.",
  },
];
